backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "contacts"
    label: "Contacts"
    folder: "src/content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Ім'я", name: "name", widget: "string" }
      - { label: "Телефон", name: "phone", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
